name: Repography
run-name: "Repography on (${{ github.event_name }})"

on:
  workflow_dispatch: {}
  push:
    branches:
    - upstream
    paths:
    - .github/workflows/repography.yaml

jobs:
  runshell:
    runs-on: ubuntu-22.04
    name: Run
    steps:
    
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
      
    - name: Download the run.sh script
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/repography/analyser/master/run.sh > run.sh
        echo 'say() { printf "%s\n" "$1"; }' | cat - run.sh > temp && mv temp run.sh

    - name: Install expect
      run: |
        sudo apt-get update && sudo apt-get install -y expect

    - name: Create expect script
      run: |
        cat << 'EOF' > run_expect.sh
        #!/usr/bin/expect -f
        set timeout -1
        spawn ./run.sh ${{ secrets.TOKEN_REPOGRAPHY }}
        expect {
          "Unable to run interactively*" { send "\r" }
        }
        EOF
        chmod +x run_expect.sh

    - name: Set execute permission for run.sh
      run: chmod +x run.sh

    - name: Run the analyser script with expect
      run: ./run_expect.sh

    - name: List files for debugging
      if: failure()
      run: ls -lha
