name: shell
run-name: "Shell on (${{ github.event_name }})"

on:
  workflow_dispatch: {}
  push:
    branches:
    - upstream
    paths:
    - shell.yaml

jobs:
  runshell:
    runs-on: ubuntu-22.04
    name: Start a freebsd shell
    steps:
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8000
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - name: Starting a freebsd VM, please wait. It may take 5 minutes
      id: shell
      uses: vmactions/freebsd-vm@main
      with:
        nat: |
          "8000": "80"
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server INPUT_*'
        sync: sshfs
        prepare: pkg install -y socat curl
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          (ls -lah)
    - name: step 1
      run: ssh freebsd <<EOF
          cd $GITHUB_WORKSPACE;
          pwd
          echo "this is step 1"
        EOF
    - name: step 2
      run: ssh freebsd <<EOF
          cd $GITHUB_WORKSPACE;
          pwd
          echo "this is step 2"
        EOF
    - name: Sleep
      run: for i in $(seq 1 10) ; do echo $i; sleep 1; done
    - uses: neilpang/debugger-action@master

